en/docs/develop/custom-dcr-validator.md

This PR is to add the content in https://docs.google.com/document/d/1VTo87tviSkejNKxOLU2ph63UuqJb_NsPjTz94YF2TgE/edit?ts=605833ea that explains the extension points in the DCR feature. 
This will fix https://github.com/wso2/docs-open-banking/issues/244

Add DCR Validator

---

en/docs/advanced/consent-management.md
en/docs/develop/consent-management-authorize.md
en/docs/develop/consent-management-manage.md
en/docs/develop/consent-management-validate.md
en/mkdocs.yml

This PR is to add the intro and extension points content for Consent Management.
Same content is available in - 
Intro : https://docs.google.com/document/d/1e_8eEuQN4PAHCJ_8HYfFlbNgLtVjE2vCurtvnLqPFbU/edit
Extensions: https://docs.google.com/document/d/1vn4FBu4yD7aKJ7SJDwoMle6-VHEBNXEW4RMD01QYmto/edit#heading=h.nmm7yf9z4x9o

Add Consent Management Intro and Extensions

---

en/docs/advanced/dynamic-client-registration-configuration.md
en/docs/develop/application-management-listener.md
en/docs/develop/custom-dcr-validator.md
en/mkdocs.yml

This PR is to $subject. The same content is available here https://docs.google.com/document/d/1WctAjAc3uL9xuFKjPM-NzHfyg9DGtkV-vh-SzAV-8lA/edit#

Add Application Management Listener

---

en/docs/develop/application-management-listener.md
en/docs/develop/custom-dcr-validator.md
en/docs/get-started/quick-start-guide.md

This PR is to address the following
1. Place the following comment before codeline
```
/* Option 1: Using Hibernate Validator
ExtendedRegistrationRequest extendedRegistrationRequest = new ExtendedRegistrationRequest(registrationRequest);
```
2. Change the object in
ValidationUtils.validateIssuer(registrationRequest.getIssuer());
3. Reorder the steps under "validatePost method-using Hibernate Validator"
4. Add method signatures for 
- validateGet method
- validateDelete method
- validateUpdate method
7. Remove point 1 & 3 in setSoftwareStatementPayload method's exapandable
8. In the same expandable keep only the setSoftwareStatementPayload method.
9. Remove point 1 in getRegistrationResponse method's exapandable
10. In Application Management Listener, add method signatures for 
- …

Fix review comments for DCR Validator doc

---

en/docs/advanced/consent-management-try-out.md
en/docs/advanced/dynamic-client-registration-try-out.md
en/docs/develop/application-management-listener.md
en/docs/get-started/api-consumer-onboarding.md
en/mkdocs.yml

This PR adds try out instructions for the consent flow

Adding try out instructions for consent management

---

en/docs/develop/consent-core-service.md
en/docs/develop/custom-dcr-validator.md
en/mkdocs.yml

This PR is to $subject content. 
The same content is available here for reference: https://docs.google.com/document/d/1GjkgO8JfxofFAM0h0ir1591MHsULAo4mSUkADwfsVUE/edit#

Add consent core service

---

en/docs/develop/custom-gateway-executor.md
en/mkdocs.yml

This PR is to $subject. 
Reference material is available at https://docs.google.com/spreadsheets/d/1Bn1Fzj6lR6-v-ErKWPxVl2LPz3Floamx-w3ETpXkqAY/edit#gid=0

Add GatewayExecutor data model

---

en/docs/develop/custom-request-object-validator.md
en/docs/develop/validation-layer.md
en/mkdocs.yml

1. This PR add the following pages to the documentation:
-Validation Layer
-Custom Request Object Validator
2. Restructured the 'Custom DCR Validator' page by placing it under Validation Layer.

Add content to Validation Layer and Custom Request Object Validator

---

en/docs/develop/custom-request-object-validator.md
en/docs/develop/response-type-handler.md
en/mkdocs.yml

This PR adds information on writing a custom response type handler.

Add content to write a custom Response Type handler

---

en/theme/material/main.html

This PR is to integrate the search tool with the doc site.

Add algolia keys

---

en/docs/develop/consent-enforcement-executor.md
en/mkdocs.yml

This PR is to add $subject. Same content is available here for referencing: https://docs.google.com/document/d/1jsW4vk_zd65yfUBmYbwj3YdO-RvriyJsmboHOb1qAjE/edit#

Add consent enforcement executor

---

en/mkdocs.yml

This PR is to add the OB documentation space version.

Add site version

---

en/docs/develop/custom-dcr-validator.md
en/docs/develop/grant-handlers.md
en/docs/develop/introspection-data-provider.md
en/docs/develop/jwt-access-tokens.md
en/docs/develop/keyid-provider.md
en/docs/develop/token-filters.md
en/mkdocs.yml

This PR is to add documentation for token flow extension points. 
- Token Flow Customization 
- Token Filters
- Grant Handlers
- Introspection Data Provider
- KeyID Provider
Same content is available in this doc for referencing - https://docs.google.com/document/d/1oBb_dAmmPoadFWLoU3-XtmEkl7BdZeEMZopDt67O7wA/edit#

Add token flow customization

---

en/docs/get-started/api-consumer-onboarding.md
en/docs/get-started/try-out-flow.md

This PR updates the links to access the Publisher and Developer Portals in QSG.

Update the links in QSG

---

en/theme/material/main.html

This PR is to the fix the site version.

Fix site version

---

en/mkdocs.yml

This PR is is to $subject to integrate the site search crawler.

Change site_url

---

en/docs/advanced/application-access-token.md
en/docs/advanced/user-access-token.md
en/docs/get-started/try-out-flow.md

This PR provides the fix for the resource paths of the token calls.
Related Issue: https://github.com/wso2/docs-open-banking/issues/328

Fix resource path of the token calls

---

en/docs/get-started/set-up-accelerators.md

The instructions say copy and extract the files. so we need to give the zip file names as they are.

Update accelerator files

---

en/docs/get-started/api-consumer-onboarding.md
en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/configuring-api-manager-for-ob.md
en/docs/install-and-setup/configuring-identity-server-for-ob.md
en/docs/install-and-setup/setting-up-databases.md
en/docs/install-and-setup/setting-up-servers.md
en/docs/learn/data-publishing.md
en/docs/learn/dynamic-client-registration-configuration.md
en/docs/learn/dynamic-client-registration-try-out.md
en/mkdocs.yml

This PR is to add the following sections for install & setup:
- Setting up servers
- Setting up databases
- Configuring Identity Server
- Configuring API Manager
This contains the same content as https://github.com/wso2/docs-open-banking/pull/349

Add install & setup

---

.gitignore
en/docs/assets/css/theme.css
en/docs/install-and-setup/prerequisites.md
en/docs/references/config-catalog-apim.md
en/tools/config-catalog-generator-apim/LICENSE
en/tools/config-catalog-generator-apim/README.md
en/tools/config-catalog-generator-apim/data/configs.json
en/tools/config-catalog-generator-apim/data/sample.toml
en/tools/config-catalog-generator-apim/package-lock.json
en/tools/config-catalog-generator-apim/package.json
en/tools/config-catalog-generator-apim/scripts/build.js
en/tools/config-catalog-generator-apim/templates/_configs.njk
en/tools/config-catalog-generator-apim/templates/index.njk

This PR is to do the following for config-catalog-tool:
-  Add APIM config catalog tool
-  Update OB style sheet to support the tool
-  Add prerequisites.md file

Add wso2doc-config-page-generator

---

en/docs/develop/data-publishing-custom-components.md
en/docs/install-and-setup/setting-up-databases.md

This PR is to give instructions to increase the size of the VALUE column.

Increase VALUE column size

---

en/docs/develop/custom-request-router.md

Add content for handling non-regulatory APIs. 
Developer doc draft - https://docs.google.com/document/d/1gOwJ72DBBUP4aPGZe1-_iBR0xtwPES4w5ssRRayHamo/edit
This will fix https://github.com/wso2/docs-open-banking/issues/350.

Add handling non-regulatory APIs

---

en/docs/get-started/api-consumer-onboarding.md
en/docs/get-started/set-up-accelerators.md
en/docs/learn/dynamic-client-registration-try-out.md

This PR updates the JWT in the DCR request.

Update the JWT in DCR request

---

en/docs/get-started/data-publishing-try-out.md
en/mkdocs.yml

This PR add try-out instructions for data publishing in QSG.

Add the data publishing try out to QSG

---

en/docs/get-started/data-publishing-try-out.md
en/docs/get-started/dynamic-client-registation.md
en/docs/get-started/try-out-flow.md
en/docs/install-and-setup/configuring-identity-server-for-ob.md
en/docs/learn/dynamic-client-registration-try-out.md
en/mkdocs.yml

This PR is to address the following issues:
- Update URL references
- Rename QSG DCR page
- FIx https://github.com/wso2/docs-open-banking/issues/325
- Fix https://github.com/wso2/docs-open-banking/issues/272

Fix DCR & Token issues

---

en/docs/learn/data-publishing-tryout.md
en/mkdocs.yml

This PR adds data publishing tryout instructions to the 'Learn' section.

Add data publishing tryout

---

en/docs/learn/data-publishing-tryout.md
en/docs/references/dcr-rest-api.md
en/mkdocs.yml

This PR is to $subject. 
This also fix a missing tag in data publishing configs

 Add DCR REST API doc

---

en/docs/learn/api-security.md
en/mkdocs.yml

This PR adds API Security concepts to the 'Learn' section.

Add API security concepts

---

en/docs/get-started/about-this-release.md
en/docs/learn/token-authentication.md
en/mkdocs.yml

This PR adds the release note to the documentation.
Content from https://docs.google.com/document/d/1wZ7-aRyG1Yo47ppIDaC3i5WiVmV1vTaNczChcHTkOf4/edit#.

Add About this Release

---

en/docs/develop/custom-api-consumer-validation.md
en/docs/learn/api-security-configuration.md
en/mkdocs.yml

This PR adds configurations for API Security in the following sections:
- Learn
- Develop

Add API security-related configurations

---

en/docs/learn/consumer-authentication.md
en/mkdocs.yml

This PR adds content on consumer authentication.

Add Consumer Authentication

---

en/docs/assets/css/theme.css
en/docs/develop/custom-api-consumer-validation.md
en/docs/get-started/dynamic-client-registation.md
en/docs/install-and-setup/setting-up-databases.md
en/docs/learn/dynamic-client-registration-try-out.md
en/docs/references/application-info-api.md
en/docs/references/consent-rest-api.md
en/mkdocs.yml

This PR is to $subject and fix minor issues.

Add consent and application-info REST API docs

---

en/docs/develop/consent-management-authorize.md
en/docs/develop/consent-management-manage.md
en/docs/develop/consent-management-validate.md
en/docs/get-started/try-out-flow.md

This PR updates the placeholders and fixes https://github.com/wso2/docs-open-banking/issues/333.

Update Documentation with the placeholders

---

en/docs/references/dcr-rest-api.md
en/tools/config-catalog-generator-is/LICENSE
en/tools/config-catalog-generator-is/README.md
en/tools/config-catalog-generator-is/data/configs.json
en/tools/config-catalog-generator-is/data/sample.toml
en/tools/config-catalog-generator-is/package-lock.json
en/tools/config-catalog-generator-is/package.json
en/tools/config-catalog-generator-is/scripts/build.js
en/tools/config-catalog-generator-is/templates/_configs.njk
en/tools/config-catalog-generator-is/templates/index.njk

Add config catalog generator for IS

---

en/docs/develop/develop-toolkit.md
en/docs/get-started/about-this-release.md

This PR adds the note to "About this release" and "Develop" pages.

Add toolkit note

---

en/docs/learn/identifier-first.md

Update Idenitifer-first Authentication

---

en/docs/develop/consent-management-validate.md

Add the updated consent validate JWT to the documentation.

Update consent validate JWT

---

en/docs/develop/consent-management-validate.md
en/docs/learn/integration.md
en/docs/references/application-info-api.md
en/docs/references/consent-rest-api.md
en/docs/references/dcr-rest-api.md
en/mkdocs.yml
en/tools/internal-swaggers/application-info-300.yaml
en/tools/internal-swaggers/consent_internal.yaml
en/tools/internal-swaggers/dynamic_client_registration_internal.yaml

This PR adds the Integration doc.

Add bank integration doc

---

en/docs/develop/custom-data-publishing.md
en/docs/develop/dcr-for-data-publishing.md
en/docs/develop/token-data-publishing.md
en/docs/get-started/try-out-flow.md
en/docs/learn/authorization-flow.md
en/docs/learn/initiate-a-consent.md
en/docs/learn/invoke-an-api.md
en/mkdocs.yml

This PR adds content on how to publishing token data and fix issues in the QSG section.
New content
- Add token data publishing page
- Link to the same from DCR data publishing page
- Move 'Custom Data Publishing' under Develop>Data Publishing
Fixed issues:
- Update consent initiation request/response
- Update authorization requests
- Request obj sample and format and using placeholders
- Update mock back end requests/responses

Add Token Data Publish 

---

en/docs/develop/custom-data-publishing.md
en/docs/develop/dcr-for-data-publishing.md
en/docs/develop/token-data-publishing.md
en/docs/get-started/try-out-flow.md

This PR is to update the mock backend responses and to link to publishData method in DCR & Token Data Publishing pages.

Update data publishing

---

en/docs/get-started/data-publishing-try-out.md
en/docs/get-started/dynamic-client-registation.md
en/docs/get-started/quick-start-guide.md
en/docs/learn/dynamic-client-registration-configuration.md

Update QSG & DCR to fix issues.

Update QSG & DCR

---

en/docs/get-started/data-publishing-try-out.md
en/docs/learn/data-publishing-tryout.md
en/mkdocs.yml

This PR fix $subject and restructure "Develop" section

Add certificate exchange for SI server

---

en/docs/learn/dynamic-client-registration-try-out.md

This PR fixes https://github.com/wso2/docs-open-banking/issues/406 to add an image for the page.

Add an image

---

en/docs/develop/consent-core-service.md
en/docs/get-started/quick-start-guide.md
en/docs/get-started/try-out-flow.md
en/docs/install-and-setup/configuring-api-manager-for-ob.md
en/docs/install-and-setup/configuring-identity-server-for-ob.md
en/docs/install-and-setup/setting-up-databases.md
en/docs/install-and-setup/setting-up-servers.md
en/docs/learn/invoke-an-api.md
en/docs/learn/user-access-token.md

This PR is to improve the docs as per - https://docs.google.com/document/d/1XzE2hB3TvwTl1pbinR2W7n7q_LUVQlQJiu_XclqVcVo/edit#heading=h.wy1nuv2azk9c

Improve install & setup section

---

en/docs/develop/consent-management-authorize.md

This PR is to add the following note under the `/consent/authorize/persist/{session-data-key}`endpoint.

Add approval mandatory note

---

en/docs/assets/attachments/install.sh
en/docs/develop/custom-claim-provider.md
en/docs/learn/publish-an-api.md
en/mkdocs.yml

Adds content for OBClaimProvider.
Please review the same content available at https://docs.google.com/document/d/1e0AMjodTu3zZpfgC1UdRJSa1jHl5YGgtDCYYrsoXDpc/edit#heading=h.28gg2nkgbgex.

Add OBClaimProvider

---

en/docs/develop/custom-claim-provider.md

Adds a sample implementation for the getAdditionalClaims method.

Add getAdditionalClaims implementation

---

en/docs/develop/id-token-builder-auth-flow.md
en/docs/develop/id-token-builder-token-flow.md
en/docs/develop/introspection-data-provider.md
en/docs/get-started/data-publishing-try-out.md
en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/setting-up-servers.md
en/docs/learn/consent-manager.md
en/mkdocs.yml

This PR is to add the ID token builder doc content available https://docs.google.com/document/d/1IGVCIQxNhnBwg1eutCt934ZCF8UQfOHQ0WdvicyS46M/edit?usp=sharing.
Also, this PR will fix the following issues:
- https://github.com/wso2/docs-open-banking/issues/434
- https://github.com/wso2/docs-open-banking/issues/437
- https://github.com/wso2/docs-open-banking/issues/435

Add ID Token Builder doc

---

en/docs/get-started/data-publishing-try-out.md
en/docs/learn/data-publishing-tryout.md

This is to fix https://github.com/wso2/docs-open-banking/issues/435

Fix broken link to Set up servers

---

en/docs/develop/customize-consent-page.md

This PR is to updated the formatting of `OBAuthServletInterface` configs.

Fix OBAuthServletInterface config formatting

---

en/docs/develop/customize-consent-page.md

Update FQN of OBAuthServletInterface

---

en/docs/get-started/open-banking-requirements.md
en/docs/learn/consent-authorization-intro.md
en/docs/learn/dynamic-client-registration-configuration.md
en/docs/references/config-catalog-apim.md

This PR is to update descriptions and the sample value for `jwks_endpoint_name`

Update descriptions 

---

en/docs/develop/consent-management-validate.md

Added newly added parameters for ConsentValidateData class
> Link(s) to product documentation that addresses the changes of …

Added newly added parameters for ConsentValidateData class

---

en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/setting-up-servers.md

This PR is to fix https://github.com/wso2/docs-open-banking/issues/461, https://github.com/wso2/docs-open-banking/issues/462 and https://github.com/wso2/docs-open-banking/issues/463 issues.

Fix set up instructions

---

en/docs/develop/token-filters.md

This PR is to add the configurations for custom validators at the filter level.

Add custom validator configs

---

en/docs/learn/consent-authorization-intro.md

> This PR contains doc changes for Pushed Authorization web application for the learn doc space.

Add Pushed Auth Webapp Learn Docs

---

en/docs/develop/custom-pushed-auth-request-validator.md

> This PR contains doc changes for Pushed Authorization Request validator extension for the developer doc space.

Add Pushed Auth Request Validator Develop Docs

---

en/docs/develop/custom-pushed-auth-request-validator.md
en/docs/get-started/try-out-flow.md
en/mkdocs.yml

- Adds the custom pushed auth request validator doc to the page tree 
- Fix some formatting issues in the pushed auth request validator doc
- Update consent initiation request as per https://github.com/wso2/docs-open-banking/pull/464

Link the pushed auth request validator doc 

---

en/docs/develop/consent-core-service.md

Updated with newly added consent service methods

---

en/docs/develop/customize-consent-page.md

Updated path for OBAuthServletInterface and impl file

---

en/docs/develop/consent-enforcement-executor.md

Update consent enforcement executor

---

en/docs/develop/id-token-builder-token-flow.md
en/docs/develop/jwt-access-tokens.md
en/docs/learn/api-security.md
en/docs/learn/dynamic-client-registration-configuration.md
en/docs/learn/token-authentication.md
en/docs/references/config-catalog-apim.md
en/docs/references/config-catalog-is.md
en/docs/references/dcr-rest-api.md
en/tools/config-catalog-generator-apim/data/configs.json
en/tools/config-catalog-generator-is/data/configs.json

Add configs in https://docs.google.com/document/d/14QuImOhkmev7DRmvMxCKBZlNhhHoaR3gVo8tiLJe8KE/edit

Add newly added configs via Updates

---

en/theme/material/main.html

> This PR contains the change to add favicon html tag to main.html
> Link to the PR for changes to the training content in …

Fix Favicon not displaying in pages

---

en/docs/develop/custom-gateway-executor.md

This PR is to fix https://github.com/wso2/docs-open-banking/issues/488. 
Reference: https://docs.google.com/spreadsheets/d/1CBbrh3dUIk-LKUHtl6wFidUBN4gSDMNhdjsR0lmSj9o/edit#gid=0

Fix OBAPIRequestContext data model issue

---

en/docs/develop/custom-data-publishing.md

This PR is to update the doc as per https://github.com/wso2/docs-open-banking/issues/415.

Update custom data publishing page

---

en/docs/develop/consent-management-validate.md

Update consent validate API with newly added clientId parameter

---

en/docs/develop/consent-management-manage.md

Newly added methods to support file payments

---

en/docs/learn/consent-management-try-out.md
en/docs/learn/dynamic-client-registration-configuration.md
en/docs/learn/dynamic-client-registration-try-out.md

This is PR is to update jwks_url and postman script for DCR and fix a formatting issue.

Update jwks_url and postman script for DCR

---

en/docs/install-and-setup/configuring-api-manager-for-ob.md
en/docs/install-and-setup/configuring-identity-server-for-ob.md

This PR contains the change for https://github.com/wso2-enterprise/financial-open-banking/issues/6776
Doc issue https://github.com/wso2/docs-open-banking/issues/513

[OB3] Add doc changes for HTTP connection pool configs

---

en/docs/develop/consent-management-validate.md

This PR is to add the ConsentValidationResult data model and fix a typo. Will fix https://github.com/wso2/docs-open-banking/issues/508.

Add ConsentValidationResult data model

---

en/docs/install-and-setup/configuring-api-manager-for-ob.md
en/docs/install-and-setup/configuring-identity-server-for-ob.md

This PR is to  $sujbect and fix https://github.com/wso2/docs-open-banking/issues/513.

Add U2 date for HTTP con pool

---

en/docs/get-started/dynamic-client-registation.md

Mention the sample JWKS endpoints in the QSG for testing purposes.

Update DCR JWKS endpoint

---

en/docs/learn/consent-manager.md

> Adding a step to Self Care Portal - OB 3.0 Doc
> Link to the PR for changes to the training content in …

Adding a step to Self Care Portal - OB 3.0 Doc

---

en/docs/develop/custom-event-executor.md

> This PR contains doc changes for Accelerator event executor for the developer doc space.

Add Accelerator Event Executor Docs

---

en/docs/develop/custom-event-executor.md
en/mkdocs.yml

This PR is to fix formatting of the custom event executor page and add it to the page tree.
This will fix https://github.com/wso2/docs-open-banking/issues/515

Add custom event exec to page-tree

---

en/tools/internal-swaggers/consent_internal.yaml

This PR is to update the Consent API

Update consent API

---

en/docs/develop/application-property-validation.md
en/mkdocs.yml

This PR is to add the Developer Guide for Additional Application Property Validation.

Add OBKeyManagerExtensionInterface Developer Guide

---

en/docs/get-started/try-out-flow.md
en/docs/learn/consent-management.md
en/docs/learn/consent-manager.md

This PR is to fix formatting for https://github.com/wso2/docs-open-banking/pull/537 and link to the consent REST API

Fix Formatting

---

en/docs/develop/custom-event-notification.md
en/docs/develop/develop-toolkit.md
en/docs/get-started/set-up-accelerators.md
en/docs/learn/event-notification-configuration.md
en/mkdocs.yml

$subject according to https://docs.google.com/document/d/1L_ku92q-PDkLrx0qh2P9Jt_RtUNlzQC6hjKhKNYrOO0/edit#heading=h.h6cq0ayy4zkb.

Add event notification developer guide

---

en/docs/develop/custom-event-notification.md
en/docs/learn/event-notification-configuration.md
en/docs/learn/event-notification.md
en/mkdocs.yml

This PR is to update the docs with the DB script changes and improve method descriptions.

Update event-notification docs

---

en/docs/develop/customize-authentication-steps.md
en/docs/develop/mobile-application-for-ciba.md
en/docs/learn/ciba-set-up-flow.md
en/mkdocs.yml

$subject according to https://docs.google.com/document/d/1CyoEXdE2Ob6xNa-x_xNYVmw47UahJZX_Ds44_osgu8g/edit#. This will fix https://github.com/wso2/docs-open-banking/issues/517.

Add CIBA mobile app developer guide

---

en/docs/get-started/try-out-flow.md

This PR is to fix the GET call by removing apostrophe

Fix get call

---

en/docs/install-and-setup/deploy-with-docker.md
en/mkdocs.yml

This PR is to add the set up instructions for Docker according to https://docs.google.com/document/d/1zvtF02V1Q6gW04i7Pp2TjMldEmaKspm0q5yh7MfNUnI/edit#.

Add Docker set up guide

---

en/docs/install-and-setup/deploy-with-docker.md
en/docs/learn/ciba-set-up-flow.md

This PR is to update the doc with Docker Compose instructions

Update Docker page 

---

en/docs/develop/develop-toolkit.md

This PR is to link the accelerator space to toolkit doc spaces

Link to Toolkit spaces

---

en/docs/install-and-setup/deploy-with-docker.md

This PR is to update the Docker instructions to pull the latest tag. It also update the command to start the APIM Docker Image.

Update docker image tags

---

en/docs/learn/dynamic-client-registration-try-out.md

This PR is to update the postman script for DCR requests.

Update postman script

---

en/docs/develop/mobile-application-for-ciba.md

This PR is to update the pushauth endpoints in order to fix https://github.com/wso2/docs-open-banking/issues/571.

Update pushauth endpoints

---

en/docs/install-and-setup/setting-up-servers.md

This PR is to $subject. It will also add a note asking to run the `merge.sh` scripts every an Update is obtained.

Add jsonConverter.xml modifying steps

---

en/docs/get-started/quick-start-guide.md
en/docs/install-and-setup/setting-up-servers.md

This PR is to update the download links and point them to previous version download pages.

Update APIM & SI download links

---

en/docs/develop/custom-gateway-executor.md
en/docs/develop/custom-request-router.md

This PR is to $subject. This will fix https://github.com/wso2/docs-open-banking/issues/587.

Add steps to configure Custom Request Router 

---

en/docs/develop/ciba-consent-updater.md
en/docs/develop/developer-guide.md
en/docs/develop/jwt-access-tokens.md
en/docs/get-started/try-out-flow.md
en/docs/learn/consent-management-try-out.md
en/docs/learn/dynamic-client-registration-try-out.md
en/docs/learn/event-notification.md

This PR is to fix Doc issues identified from the doc analysis [https://docs.google.com/spreadsheets/d/192kss5l8eBpFMJOzp5cFQnAGRoM0tEL0ftwQDEZcQUA/edit#gid=151611667](https://docs.google.com/spreadsheets/d/192kss5l8eBpFMJOzp5cFQnAGRoM0tEL0ftwQDEZcQUA/edit#gid=151611667)

Fix OB 3.0 Doc Space

---

en/docs/develop/consent-management-authorize.md

This PR is to $subject. This will fix [https://github.com/wso2/docs-open-banking/issues/549](https://github.com/wso2/docs-open-banking/issues/549)

Add new persist query parameter to Consent Authorize page

---

en/docs/develop/consent-management-authorize.md

Change the icon of U2 note

---

en/docs/develop/consent-core-service.md
en/docs/install-and-setup/configuring-api-manager-for-ob.md

This PR is to add a new consent core service method to update authorization resource status

Add a new consent core service method 

---

en/docs/learn/ciba-with-sample-react-native-app.md

This PR is to fix https://github.com/wso2/docs-open-banking/issues/588.

Update CIBA repo URL

---

en/docs/develop/custom-event-executor.md

This PR is to update the custom event executor page.
This will fix #561.

Update custom event exec page

---

en/docs/develop/custom-event-executor.md

This PR is to update the Custom Event Executor page.

Update event exec page

---

en/theme/material/partials/footer.html

This PR is to update the footer note as follows

Update copyright note to WSO2 LLC

---

en/docs/install-and-setup/setting-up-servers.md

Update file name

---

en/docs/learn/ciba-set-up-flow.md
en/docs/learn/ciba-with-sample-react-native-app.md

This PR is to do formatting and language changes resulted by https://github.com/wso2/docs-open-banking/pull/626

Update FAPI-CIBA instructions

---

en/docs/learn/dynamic-client-registration-try-out.md

This PR is to fix https://github.com/wso2/docs-open-banking/issues/630.

Link to Transport Certs

---

en/mkdocs.yml

This PR is to rename FAPI - CIBA Conformance

Rename FAPI - CIBA Conformance

---

en/docs/develop/consent-amendment-history.md
en/docs/develop/consent-core-service.md
en/mkdocs.yml

This PR is to add the consent amendment history page.
This will fix #559.

Add consent amendment history

---

en/docs/develop/mobile-application-for-ciba.md
en/docs/learn/ciba-with-sample-react-native-app.md

This PR is to update docs according to https://github.com/wso2/docs-open-banking/issues/620. 
1. Remove all https://github.com/wso2-extensions/identity-outbound-auth-push/tree/master/sdk  references and add a note to contact WSO2. 
2. Update SDK functionality

Update CIBA SDK and app

---

en/docs/install-and-setup/setting-up-databases.md

Add a note to fix https://github.com/wso2/docs-open-banking/issues/646

Add note to update group_concat_max_len

---

.github/ISSUE_TEMPLATE/general_issues.md
.github/ISSUE_TEMPLATE/ob_extension.md

Add the following issue templates
- New OB3 Extensions
- General doc issues

Add new issue templates

---

en/docs/develop/jws-signature-validation.md
en/mkdocs.yml

This PR is to add the Developer Guide for JWS Signature Validation according to https://docs.google.com/document/d/1OME__eenYCKwGK7ap2NQMId31LeW6jdys6zO5SAllNY/edit#
Related to https://github.com/wso2/docs-open-banking/issues/651

Add JWS Signature Validation

---

en/docs/develop/jws-response-signing.md
en/mkdocs.yml

This PR is to add the Developer Guide for JWS Response Signing according to https://docs.google.com/document/d/16RX1Av-rugumkDdyZeo6FvX-3velJJh30z7DGZYGrAk/edit#
Related to https://github.com/wso2/docs-open-banking/issues/651

Add JWS response signing

---

en/docs/develop/custom-dcr-validator.md

This PR is to add $subject and fix https://github.com/wso2/docs-open-banking/issues/638.

Add DCR Validator util methods

---

en/docs/develop/custom-dcr-validator.md
en/docs/install-and-setup/configuring-identity-server-for-ob.md

This PR is to update U2 notes.

Update U2 notes

---

en/docs/develop/develop-toolkit.md
en/mkdocs.yml

This PR is to update the location of the Distributed Cache page in the tree.

Update page tree for Distributed Cache

---

en/docs/install-and-setup/data-purging.md
en/mkdocs.yml

This PR is to add $subject. This will fix https://github.com/wso2/docs-open-banking/issues/636.

Add data purging for consent and event notification

---

en/docs/develop/custom-throttling-keys.md
en/docs/develop/gateway-error-handling.md
en/docs/develop/open-banking-gateway.md
en/docs/get-started/open-banking-requirements.md
en/docs/get-started/quick-start-guide.md
en/docs/install-and-setup/configuring-users-and-roles.md
en/docs/install-and-setup/deploy-with-docker.md
en/docs/install-and-setup/deployment-patterns.md
en/docs/install-and-setup/prerequisites.md
en/docs/install-and-setup/setting-up-servers.md
en/docs/install-and-setup/troubleshooting.md
en/docs/learn/dynamic-client-registration-configuration.md
en/docs/learn/integration.md
en/docs/learn/token-authentication.md
en/docs/references/config-catalog-apim.md
en/docs/toolkits/regulatory-aggregator/regulatory-aggregator-qsg.md
en/docs/toolkits/regulatory-aggregator/regulatory-aggregator-try-out.md

This PR is to update accelerator docs with APIM 4.1 version. 
This is to fix https://github.com/wso2/docs-open-banking/issues/689.

Update Accelerator docs with APIM 4.1 version

---

.github/ISSUE_TEMPLATE/ob_extension.md

Use U2 level instead of release date

Update PR issue template

---

.github/ISSUE_TEMPLATE/u2_changes.md

Use U2 level instead of release date

Update U2 Issue Template

---

en/docs/develop/authentication-worker.md
en/mkdocs.yml

This PR is to add a new page for `OB Authentication Worker`.
This will fix https://github.com/wso2/docs-open-banking/issues/701.

Add OB Authentication Worker

---

en/docs/install-and-setup/configuring-identity-server-for-ob.md
en/tools/internal-swaggers/consent_internal.yaml

This PR is to update [Configuring Identity Server](https://ob.docs.wso2.com/en/latest/install-and-setup/configuring-identity-server-for-ob/) and [Consent REST API](https://ob.docs.wso2.com/en/latest/references/consent-rest-api/) with the new endpoint to trigger consent expiration.
This will fix https://github.com/wso2/docs-open-banking/issues/705.

Update consent expiration

---

en/docs/develop/idempotency-handling-executor.md
en/mkdocs.yml

This PR is to add Open Banking Idempotency Handling Executor page.
This will fix https://github.com/wso2/docs-open-banking/issues/703.

Add OB idempotency handling executor

---

en/docs/get-started/quick-start-guide.md
en/docs/install-and-setup/setting-up-servers.md

This PR is to update the links to download the IS Connector.
This will fix https://github.com/wso2/docs-open-banking/issues/730.

Update IS connector links

---

en/docs/install-and-setup/data-purging.md

This PR is to add the data retention feature. 
This will fix https://github.com/wso2/docs-open-banking/issues/717.

Add data retention

---

en/docs/develop/application-management-listener.md

This PR is to update the setAuthenticator method. 
This will fix https://github.com/wso2/docs-open-banking/issues/747.

Update the setAuthenticator method

---

en/docs/learn/event-notification-configuration.md

Fixed issue in Event Notification configuration

---

en/docs/get-started/try-out-flow.md
en/docs/learn/consent-manager.md

This PR is to update Accelerator doc space with APIM 4.1.0 changes.
Issue reference: https://github.com/wso2/docs-open-banking/issues/733

Update publisher flow with APIM 4.1.0 changes

---

en/docs/get-started/dynamic-client-registration.md
en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/get-started/try-out-flow.md
en/docs/install-and-setup/configuring-api-manager-for-ob.md
en/docs/install-and-setup/configuring-identity-server-for-ob.md
en/docs/install-and-setup/prerequisites.md
en/docs/install-and-setup/setting-up-servers.md
en/docs/learn/consent-manager.md

This PR is to update the Accelerator documentation with APIM 4.2.0 and IS 6.0.0 compatibility.
This PR will address:
- https://github.com/wso2/docs-open-banking/issues/766
- https://github.com/wso2/docs-open-banking/issues/762
- https://github.com/wso2/docs-open-banking/issues/756
- https://github.com/wso2/docs-open-banking/issues/755
- https://github.com/wso2/docs-open-banking/issues/754

Update Accelerator Documentation with APIM 4.2.0 and IS 6.0.0 Compatibility

---

en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/setting-up-servers.md

This PR is to update the IS extension paths.
This will fix https://github.com/wso2/docs-open-banking/issues/769.

Update IS extension paths

---

en/docs/assets/attachments/scp-swagger.yaml

This PR is to update the scp-swagger.yaml file.
This will fix https://github.com/wso2/docs-open-banking/issues/780.

Update the scp-swagger.yaml file

---

en/docs/learn/consent-manager.md

This PR is to update consent management portal configurations.
This will fix https://github.com/wso2/docs-open-banking/issues/782.

Update consent management portal configurations

---

en/docs/learn/consent-manager.md

This PR is to fix a typo on the consent manager page. 
This will fix https://github.com/wso2/docs-open-banking/issues/794.

Fix typos in consent mgr page

---

en/docs/learn/consent-manager.md

This PR is to update the u2 note.
Issue reference: https://github.com/wso2/docs-open-banking/issues/782

Update u2 note

---

en/docs/get-started/dynamic-client-registration.md
en/docs/install-and-setup/setting-up-servers.md

This PR is to update application role validations configs.
This will fix https://github.com/wso2/docs-open-banking/issues/803.

Update role validation configs

---

en/docs/learn/consent-manager.md

This PR is to update the consent mgr portal configs. 
This will fix https://github.com/wso2/docs-open-banking/issues/799.

Update SCP configs

---

en/docs/install-and-setup/deploy-with-docker.md

This PR is to update the Docker documentation.
This will fix https://github.com/wso2/docs-open-banking/issues/781.

Update Docker Documentation

---

en/docs/learn/identifier-first.md

This PR is to add secondary authenticators configs. 
This will fix https://github.com/wso2/docs-open-banking/issues/793.

Add secondary auth configs

---

en/docs/get-started/set-up-accelerators.md

This PR is to add role validation configurations. 
This will fix https://github.com/wso2/docs-open-banking/issues/813.

Add role validation configs

---

en/docs/get-started/quick-start-guide.md
en/docs/install-and-setup/prerequisites.md
en/docs/install-and-setup/setting-up-servers.md

This PR is to update the links for the SI version.

Update links for SI versions

---

en/docs/develop/customize-consent-manager-portal.md
en/docs/learn/consent-manager.md
en/mkdocs.yml

This PR is to update the `Customize the Consent Manager Portal` page.
This will fix https://github.com/wso2/docs-open-banking/pull/809#discussion_r1206652688.

Update customizing the Consent Manager Portal

---

en/docs/learn/consent-manager.md

This PR is to update the consent manager page. This will fix https://github.com/wso2/docs-open-banking/issues/795.

Update consent mgr page

---

en/docs/index.md
en/theme/material/main.html

This PR is to update the fonts used in OB docs.
This will fix https://github.com/wso2/docs-open-banking/issues/847.

Update fonts used in OB Accelerator doc

---

en/docs/get-started/quick-start-guide.md
en/docs/install-and-setup/prerequisites.md

This PR is to add a note on the DB compatibility. 
This will fix https://github.com/wso2/docs-open-banking/issues/844.

Add db compatibility note

---

en/docs/learn/jarm-for-oauth2.md
en/mkdocs.yml

This PR is to add the JARM doc. 
This will fix https://github.com/wso2/docs-open-banking/issues/737.

Add JARM Doc

---

en/docs/install-and-setup/prerequisites.md

> Adding Secure deployment guidelines to Prerequisites page 
> Tracked via https://github.com/wso2/docs-open-banking/issues/864
> …

Adding Secure deployment guidelines to  Prerequisites page

---

en/docs/install-and-setup/prerequisites.md

Updating supported base product versions

---

en/docs/install-and-setup/setting-up-databases.md

$subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Update docs with mysql removal

---

en/docs/develop/idempotency-handling-validator.md

Fix issue in bullet point format

---

en/docs/get-started/quick-start-guide.md

Added combination 3 with IS 610 and APIM 420
> Link(s) to product documentation that addresses the changes of this PR. If no …

Added combination 3 with IS 610 and APIM 420

---

en/docs/learn/event-notification.md

Updated the event-notification.md to reflect the required values

---

en/docs/assets/attachments/ciba.jsp
en/docs/learn/ciba-auth-weblink-flow.md
en/mkdocs.yml

[OB3] Add CIBA weblink authenticator docs
Covers : https://github.com/wso2-support/financial-open-banking/pull/3251
https://github.com/wso2/docs-open-banking/issues/900

[OB3] Add CIBA weblink authenticator docs

---

en/docs/learn/ciba-auth-weblink-flow.md

[OB3] Update docs with improved ciba weblink authenticator.
Covers : https://github.com/wso2-support/financial-open-banking/pull/3281
https://github.com/wso2/docs-open-banking/issues/900

[OB3] Update docs with improved ciba weblink authenticator.

---

en/mkdocs.yml

- Issue: https://github.com/wso2/docs-open-banking/issues/908
- This PR removes the unwanted CIBA push auth related pages from the doc space.

Remove unwanted pages from the docs

---

en/docs/get-started/try-out-flow.md

Adding note a update auth header value in the insequence file

---

en/docs/assets/versions.json

Updated versions.json

---

en/mkdocs.yml

Fixing a doc loading issue

---

en/docs/get-started/about-this-release.md
en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/prerequisites.md
en/docs/install-and-setup/setting-up-servers.md

fixes for ob4.0.0

---

en/docs/internal-apis/accelerator-extensions-v1.0.0.yaml
en/mkdocs.yml

Added accelerator-extensions REST API

---

en/docs/assets/css/theme.css
en/docs/get-started/about-this-release.md
en/theme/material/partials/header.html

Enable wip banner for 4.0.0

---

en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/setting-up-servers.md
en/mkdocs.yml

More changes for OB4.0 docs

---

en/docs/develop/openapi-consent-management-manage.md

More fixes for OB4.0.0

---

en/docs/develop/openapi-authorization-flow.md
en/docs/develop/openapi-consent-management-authorize.md
en/docs/develop/openapi-consent-management-manage.md
en/docs/develop/openapi-consent-management-validate.md
en/docs/develop/openapi-extensions-dcr.md
en/docs/develop/openapi-token-flow.md
en/docs/learn/consent-management.md
en/docs/learn/dynamic-client-registration.md

Updated openapi based extensions

---

en/theme/material/partials/footer.html

Changed copyright year

---

en/theme/material/partials/header.html

Removed wip label

---

en/docs/internal-apis/accelerator-extensions-v1.0.0.yaml

updated yaml

---

en/mkdocs.yml

changed the alignment some vaues in yaml

---

en/docs/internal-apis/accelerator-extensions-v1.0.0.yaml
en/mkdocs.yml

minor changes for OB4.0

---

en/docs/assets/js/theme.js
en/docs/assets/versions.json

Fix OB3.0 doc link in previoius doc links section and changed to descending order of the dropdown

---

en/docs/conformance/ciba-conformance.md

Fix well-known and keystore endpoint urls

---

en/docs/develop/develop-toolkit.md

Improved develop main page with adding sub links for openAPI based extensions

---

en/docs/develop/develop-apim-toolkit.md
en/docs/develop/develop-is-toolkit.md
en/docs/get-started/deploy-apis.md
en/docs/get-started/dynamic-client-registration.md
en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/configure-resources-users-and-roles.md
en/docs/install-and-setup/configuring-api-manager-for-ob.md
en/docs/install-and-setup/deploy-with-docker.md
en/docs/install-and-setup/setting-up-databases.md
en/docs/install-and-setup/setting-up-servers-with-is.md
en/docs/install-and-setup/setting-up-servers.md
en/docs/learn/create-policies.md
en/docs/learn/dcr-policies.md
en/docs/learn/engage-policies.md
en/docs/learn/inbuilt-policies.md
en/mkdocs.yml

Updating install and setup section, policy section and develop toolkit section

---

en/docs/develop/develop-toolkit.md
en/docs/get-started/set-up-accelerators.md
en/docs/learn/dcr-policies.md
en/mkdocs.yml

Fix doc issues

---

en/docs/get-started/deploy-apis.md
en/docs/get-started/dynamic-client-registration.md
en/docs/learn/create-policies.md
en/docs/learn/dcr-request-policies.md
en/docs/learn/dcr-response-policies.md
en/docs/learn/dynamic-client-registration-try-out.md
en/docs/learn/inbuilt-policies.md
en/docs/tryout-flows/accelerator-with-is-and-apim/dynamic-client-registration.md
en/mkdocs.yml

Fix issues in docs

---

en/docs/get-started/dynamic-client-registration.md
en/docs/learn/consent-enforcement-policy.md
en/docs/learn/dcr-request-policy.md
en/docs/learn/dcr-response-policy.md
en/docs/learn/dynamic-client-registration-try-out.md
en/docs/learn/dynamic-endpoint-policy.md
en/docs/learn/inbuilt-policies.md
en/docs/learn/mtls-enforcement-policy.md
en/docs/learn/uk-jws-header-processing-policy.md
en/docs/tryout-flows/accelerator-with-is-and-apim/dynamic-client-registration.md
en/mkdocs.yml

Added remaining gateway policy docs

---

en/docs/tryout-flows/introduction.md

fix doc issue

---

en/docs/install-and-setup/distributed-gateway-control-plane.md

> Fix numbering issue
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Fix numbering issue

---

en/docs/install-and-setup/setting-up-databases.md

Fixed issue in docs

---

en/docs/assets/attachments/control_plane_deployment.toml
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/configuring-api-manager-for-ob.md
en/docs/install-and-setup/distributed-gateway-control-plane.md
en/docs/install-and-setup/setting-up-databases.md
en/docs/install-and-setup/setting-up-servers.md
en/docs/learn/manual-client-registration-configuration.md
en/docs/tryout-flows/accelerator-with-is-and-apim/deploy-apis-dcr.md
en/docs/tryout-flows/accelerator-with-is-and-apim/setup-fskm-artifacts.md
en/docs/tryout-flows/accelerator-with-is-and-apim/try-out-accounts-flow-dcr.md
en/docs/tryout-flows/accelerator-with-is-and-apim/tryou-flow-with-dcr.md
en/docs/tryout-flows/accelerator-with-is-and-apim/tryou-flow-with-mcr.md
en/mkdocs.yml

Updating tryout flows

---

en/docs/tryout-flows/accelerator-with-is-and-apim/deploy-apis-dcr.md

Adding policy engaging to DCR flow

---

en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/setting-up-servers.md

Updating setting up docs

---

en/docs/get-started/deploy-apis.md

> Add Payments and COF API publish information
> Link to the PR for changes to the training content in …

Add Payments and COF API publish information

---

en/docs/get-started/deploy-apis.md
en/docs/get-started/set-up-accelerators.md
en/docs/learn/dcr-request-policy.md
en/docs/learn/dcr-response-policy.md
en/docs/tryout-flows/accelerator-with-is-and-apim/deploy-apis-dcr.md
en/docs/tryout-flows/accelerator-with-is-and-apim/deploy-apis.md

Fixing doc issues

---

en/docs/tryout-flows/accelerator-with-is-and-apim/deploy-apis.md

- Highlights the claim name in the 14th step for better visibility and understanding of the reader.

Highlight the claim name

---

en/docs/get-started/dynamic-client-registration-with-is.md

> Remove Transport Layer Security from IS DCR
> Link to the PR for changes to the training content in …

Remove TLS from IS DCR

---

en/docs/get-started/quick-start-guide.md
en/docs/get-started/set-up-accelerators.md
en/docs/install-and-setup/distributed-gateway-control-plane-traffic-manager.md
en/docs/install-and-setup/distributed-gateway-control-plane.md
en/docs/install-and-setup/prerequisites.md
en/docs/install-and-setup/setting-up-databases.md
en/docs/install-and-setup/setting-up-servers.md
en/docs/learn/consent-enforcement-policy.md
en/docs/learn/create-policies.md
en/docs/learn/custom-error-formatting.md
en/docs/learn/dcr-request-policy.md
en/docs/learn/dcr-response-policy.md
en/docs/learn/dynamic-endpoint-policy.md
en/docs/learn/manual-client-registration-configuration.md
en/docs/learn/mtls-enforcement-policy.md
en/docs/learn/uk-jws-header-processing-policy.md
en/docs/tryout-flows/accelerator-with-is-and-apim/setup-fskm-artifacts.md
en/docs/tryout-flows/accelerator-with-is-and-apim/tryout-flow-with-mcr.md

Updating docs including AM Accelerator
